# Generated by Django 5.2.14 on 2026-05-16 18:53

import django.core.validators
import django.db.models.deletion
import shop.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=180, verbose_name='заголовок')),
                ('summary', models.CharField(max_length=255, verbose_name='краткое содержание')),
                ('content', models.TextField(verbose_name='текст статьи')),
                ('image_url', models.URLField(blank=True, verbose_name='изображение')),
                ('published_at', models.DateTimeField(verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория товара',
                'verbose_name_plural': 'категории товаров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=160, verbose_name='название компании')),
                ('about', models.TextField(verbose_name='о компании')),
                ('requisites', models.TextField(blank=True, verbose_name='реквизиты')),
                ('logo_url', models.URLField(blank=True, verbose_name='логотип')),
            ],
            options={
                'verbose_name': 'информация о компании',
                'verbose_name_plural': 'информация о компании',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('question', models.CharField(max_length=255, verbose_name='вопрос')),
                ('answer', models.TextField(verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'термин и понятие',
                'verbose_name_plural': 'словарь терминов и понятий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=160, verbose_name='точка самовывоза')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('schedule', models.CharField(max_length=160, verbose_name='график')),
            ],
            options={
                'verbose_name': 'точка самовывоза',
                'verbose_name_plural': 'точки самовывоза',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='код')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('discount_percent', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='скидка, %')),
                ('active', models.BooleanField(default=True, verbose_name='действует')),
                ('valid_until', models.DateField(verbose_name='действует до')),
            ],
            options={
                'verbose_name': 'промокод',
                'verbose_name_plural': 'промокоды и купоны',
                'ordering': ['-active', 'valid_until'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='название')),
                ('address', models.CharField(max_length=255, verbose_name='адрес')),
                ('phone', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +375 (29) XXX-XX-XX.', regex='^\\+375 \\((25|29|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'поставщик',
                'verbose_name_plural': 'поставщики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('title', models.CharField(max_length=160, verbose_name='вакансия')),
                ('description', models.TextField(verbose_name='описание')),
                ('salary', models.CharField(blank=True, max_length=120, verbose_name='зарплата')),
                ('active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'вакансия',
                'verbose_name_plural': 'вакансии',
                'ordering': ['-active', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('full_name', models.CharField(max_length=180, verbose_name='ФИО')),
                ('birth_date', models.DateField(validators=[shop.validators.validate_adult], verbose_name='дата рождения')),
                ('phone', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +375 (29) XXX-XX-XX.', regex='^\\+375 \\((25|29|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='телефон')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'постоянный клиент',
                'verbose_name_plural': 'постоянные клиенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('full_name', models.CharField(max_length=180, verbose_name='ФИО')),
                ('birth_date', models.DateField(validators=[shop.validators.validate_adult], verbose_name='дата рождения')),
                ('position', models.CharField(max_length=120, verbose_name='должность')),
                ('phone', models.CharField(max_length=19, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате +375 (29) XXX-XX-XX.', regex='^\\+375 \\((25|29|33|44)\\) \\d{3}-\\d{2}-\\d{2}$')], verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('photo_url', models.URLField(blank=True, verbose_name='фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='артикул')),
                ('name', models.CharField(max_length=160, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='розничная цена')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image_url', models.URLField(blank=True, verbose_name='ссылка на изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=120, verbose_name='имя')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('text', models.TextField(verbose_name='текст')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='дата продажи')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.employee')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promocode')),
            ],
            options={
                'verbose_name': 'продажа',
                'verbose_name_plural': 'продажи',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за единицу')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='shop.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.sale')),
            ],
            options={
                'verbose_name': 'позиция продажи',
                'verbose_name_plural': 'позиции продаж',
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('current_purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='текущая закупочная цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='активно')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.supplier')),
            ],
            options={
                'verbose_name': 'товар поставщика',
                'verbose_name_plural': 'товары поставщиков',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='suppliers',
            field=models.ManyToManyField(related_name='products', through='shop.SupplierProduct', to='shop.supplier'),
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('effective_date', models.DateField(verbose_name='дата изменения')),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='новая цена')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='shop.supplierproduct')),
            ],
            options={
                'verbose_name': 'изменение цены поставщика',
                'verbose_name_plural': 'изменения цен поставщиков',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('purchase_date', models.DateField(verbose_name='дата закупки')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за единицу')),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='shop.supplierproduct')),
            ],
            options={
                'verbose_name': 'закупка у поставщика',
                'verbose_name_plural': 'закупки у поставщиков',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='unique_supplier_product'),
        ),
    ]
